name: Deploy Web App

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch, adjust as necessary

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version
      - name: Install dependencies
        run: npm install
      - name: Build web frontend
        run: npm run build  # This should be your frontend build command
      - name: Deploy to GitHub Pages
        run: npm run deploy